spring:
  security:
    oauth2:
      client:
        registration:
          42seoul:
            client-id: u-s4t2ud-5ea817e12378a0c49e7619b430ca649d671fc6764a8b252bf0dd3f09febf76c5
            client-secret: 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
            redirect-uri: http://13.209.149.15:8080/login/oauth2/code/42seoul
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
        provider:
          42seoul:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: id
#jwt:
#  token:
#    secret: NiOeyFbN1Gqo10bPgUyTFsRMkJpGLXSvGP04eFqj5B30r5TcrtlSXfQ7TndvYjNvfkEKLqILn0j1SmKODO1Yw3JpBBgI3nVPEahqxeY8qbPSFGyzyEVxnl4AQcrnVneI
#
#accesstoken:
#  expiration:
#    time: 60000
#
#refreshtoken:
#  expiration:
#    time: 12096
#
#issuer: where42
