spring:
  security:
    oauth2:
      client:
        registration:
          42seoul:
            client-id: u-s4t2ud-605c39a02dbc646115a922e2528e128c84c61113f0479035c81e653dd15fa395
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/42seoul
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
        provider:
          42seoul:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: id
